### ISSUE TITLE
Não Conformidades

### ISSUE THREAD

**Issue by jonathanots** [Carlos-Henreis/COM212Final#2]
Segue anexo um arquivo .doc com as não conformidades encontradas nos artefatos, o arquivo possui uma tabela que identifica a data em que a NC foi registrada, a não conformidade, quem registrou, e uma descrição para apoiá-los, então vocês devem preencher as colunas: ações tomadas, quem realizou e a data de realização da ação.
[Não conformidades.docx](https://github.com/Carlos-Henreis/COM212Final/files/1412823/Nao.conformidades.docx)

**Comment by Carlos-Henreis** [comment]
Ok até semana que vem resolvemos isso e essa Issue pode ser fechada @jeanoliveira92

**Comment by mateushtoledo** [comment]
Documento de requisitos e cronograma alterados, corrigindo as inconformidades. O tópico será fechado.
